### PR TITLE
Update _home.scss

### PR DESCRIPTION
**Pull request by Mannriah**
Fixed height issue - ratio wasn't being maintained if width was shrunk.

### CODE REVIEW

**Comment by Mannriah** [comment]
> LGTM! Can you please set the target branch to `dev`?
> 
> `master` is the current release/live branch

**Comment by Mannriah** [comment]
> LGTM! Can you please set the target branch to `dev`?
> 
> `master` is the current release/live branch

I thought I selected Dev? When I make the change there is a drop down and I clicked Dev. Am I doing it wrong? :(

**Comment by Mannriah** [comment]
> Your other PR is targetting dev, but this one is still targetting master. Did you forget to updats this one? 😆

Url, i'm a noob, i'll just see myself out 🤣

**Comment by andyksaw** [comment]
Press the [Edit] button to change the 'base branch' (which will be the target of the PR)

**Comment by Mannriah** [comment]
> 
> 
> Press the [Edit] button to change the 'base branch' (which will be the target of the PR)
> 
> 

Ahh, got it, all done!

**Comment by andyksaw** [comment]
And then feel free to press the big green merge button 😉

**Comment by Mannriah** [comment]
> And then feel free to press the big green merge button 😉

Done, but i'm not sure if its working because the announcements don't appear on dev 😬

**Pull request merged**
